In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv("ecommerce_customer_churn_dataset.csv")

df.head()

,Age,Gender,Country,City,Membership_Years,Login_Frequency,Session_Duration_Avg,Pages_Per_Session,Cart_Abandonment_Rate,Wishlist_Items,...,Email_Open_Rate,Customer_Service_Calls,Product_Reviews_Written,Social_Media_Engagement_Score,Mobile_App_Usage,Payment_Method_Diversity,Lifetime_Value,Credit_Balance,Churned,Signup_Quarter
0,43.0,Male,France,Marseille,2.9,14.0,27.4,6.0,50.6,3.0,...,17.9,9.0,4.0,16.3,20.8,1.0,953.33,2278.0,0,Q1
1,36.0,Male,UK,Manchester,1.6,15.0,42.7,10.3,37.7,1.0,...,42.8,7.0,3.0,NaN,23.3,3.0,1067.47,3028.0,0,Q4
2,45.0,Female,Canada,Vancouver,2.9,10.0,24.8,1.6,70.9,1.0,...,0.0,4.0,1.0,NaN,8.8,NaN,1289.75,2317.0,0,Q4
3,56.0,Female,USA,New York,2.6,10.0,38.4,14.8,41.7,9.0,...,41.4,2.0,5.0,85.9,31.0,3.0,2340.92,2674.0,0,Q1
4,35.0,Male,India,Delhi,3.1,29.0,51.4,NaN,19.1,9.0,...,37.9,1.0,11.0,83.0,50.4,4.0,3041.29,5354.0,0,Q4

In [4]:
df.shape

(50000, 25)

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            47505 non-null  float64
 1   Gender                         50000 non-null  object
 2   Country                        50000 non-null  object
 3   City                           50000 non-null  object
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  float64
 6   Session_Duration_Avg           46601 non-null  float64
 7   Pages_Per_Session              47000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 46000 non-null  float64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       47000 non-null  float64
 13  Discount_Usage_Rate            46500 non-null  float64
 14  Returns_Rate                   45509 non-null  float64
 15  Email_Open_Rate                47472 non-null  float64
 16  Customer_Service_Calls         49832 non-null  float64
 17  Product_Reviews_Written        46500 non-null  float64
 18  Social_Media_Engagement_Score  44000 non-null  float64
 19  Mobile_App_Usage               45000 non-null  float64
 20  Payment_Method_Diversity       47500 non-null  float64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 44500 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  object
dtypes: float64(20), int64(1), object(4)
memory usage: 9.5+ MB

In [9]:
missing = df.isnull().sum()

missing = missing[missing > 0].sort_values(ascending=False)

print(missing)

Social_Media_Engagement_Score    6000
Credit_Balance                   5500
Mobile_App_Usage                 5000
Returns_Rate                     4491
Wishlist_Items                   4000
Discount_Usage_Rate              3500
Product_Reviews_Written          3500
Session_Duration_Avg             3399
Pages_Per_Session                3000
Days_Since_Last_Purchase         3000
Email_Open_Rate                  2528
Payment_Method_Diversity         2500
Age                              2495
Customer_Service_Calls            168
dtype: int64

In [10]:
duplicates = df.duplicated().sum()

print("Number of duplicated rows:", duplicates)

Number of duplicated rows: 0

In [11]:
df = df.drop_duplicates().reset_index(drop=True)

In [12]:
text_columns = df.select_dtypes(include="object").columns

for col in text_columns:
    df[col] = df[col].str.strip()

In [13]:
df["Gender"] = df["Gender"].str.title()
df["Country"] = df["Country"].str.strip()
df["City"] = df["City"].str.title()
df["Signup_Quarter"] = df["Signup_Quarter"].str.upper().str.strip()

In [14]:
for col in text_columns:
    print(col, df[col].unique())

Gender ['Male' 'Female' 'Other']
Country ['France' 'UK' 'Canada' 'USA' 'India' 'Japan' 'Germany' 'Australia']
City ['Marseille' 'Manchester' 'Vancouver' 'New York' 'Delhi' 'Tokyo' 'Berlin'
 'Houston' 'Calgary' 'Glasgow' 'Munich' 'Phoenix' 'Paris' 'Ottawa'
 'Los Angeles' 'Bangalore' 'Adelaide' 'Yokohama' 'Sydney' 'Nagoya'
 'Frankfurt' 'Cologne' 'Hamburg' 'Nice' 'Chicago' 'Toulouse' 'Brisbane'
 'Leeds' 'Mumbai' 'Montreal' 'Melbourne' 'Osaka' 'Lyon' 'Hyderabad'
 'Chennai' 'Birmingham' 'London' 'Toronto' 'Perth' 'Kyoto']
Signup_Quarter ['Q1' 'Q4' 'Q2' 'Q3']

In [15]:
df.loc[(df["Age"] < 18) | (df["Age"] > 100), "Age"] = np.nan

In [16]:
df.loc[
    (df["Cart_Abandonment_Rate"] < 0) |
    (df["Cart_Abandonment_Rate"] > 100),
    "Cart_Abandonment_Rate"
] = np.nan

In [17]:
df.loc[df["Total_Purchases"] < 0, "Total_Purchases"] = np.nan

In [18]:
df.loc[
    (df["Discount_Usage_Rate"] < 0) |
    (df["Discount_Usage_Rate"] > 100),
    "Discount_Usage_Rate"
] = np.nan

In [19]:
df.loc[
    (df["Returns_Rate"] < 0) |
    (df["Returns_Rate"] > 100),
    "Returns_Rate"
] = np.nan

In [20]:
df.loc[
    (df["Email_Open_Rate"] < 0) |
    (df["Email_Open_Rate"] > 100),
    "Email_Open_Rate"
] = np.nan

In [21]:
df.loc[
    (df["Social_Media_Engagement_Score"] < 0) |
    (df["Social_Media_Engagement_Score"] > 100),
    "Social_Media_Engagement_Score"
] = np.nan

In [22]:
df.loc[
    (df["Mobile_App_Usage"] < 0) |
    (df["Mobile_App_Usage"] > 100),
    "Mobile_App_Usage"
] = np.nan

In [23]:
non_negative_columns = [
    "Membership_Years",
    "Login_Frequency",
    "Session_Duration_Avg",
    "Pages_Per_Session",
    "Wishlist_Items",
    "Days_Since_Last_Purchase",
    "Customer_Service_Calls",
    "Product_Reviews_Written",
    "Lifetime_Value",
    "Credit_Balance"
]

for col in non_negative_columns:
    df.loc[df[col] < 0, col] = np.nan

In [24]:
df.loc[
    (df["Payment_Method_Diversity"] < 1) |
    (df["Payment_Method_Diversity"] > 5),
    "Payment_Method_Diversity"
] = np.nan

In [25]:
numeric_columns = df.select_dtypes(include=np.number).columns

numeric_columns

Index(['Age', 'Membership_Years', 'Login_Frequency', 'Session_Duration_Avg',
       'Pages_Per_Session', 'Cart_Abandonment_Rate', 'Wishlist_Items',
       'Total_Purchases', 'Average_Order_Value', 'Days_Since_Last_Purchase',
       'Discount_Usage_Rate', 'Returns_Rate', 'Email_Open_Rate',
       'Customer_Service_Calls', 'Product_Reviews_Written',
       'Social_Media_Engagement_Score', 'Mobile_App_Usage',
       'Payment_Method_Diversity', 'Lifetime_Value', 'Credit_Balance',
       'Churned'],
      dtype='object')

In [26]:
for col in numeric_columns:
    if col != "Churned":
        df[col] = df[col].fillna(df[col].median())

In [27]:
categorical_columns = df.select_dtypes(include="object").columns

for col in categorical_columns:
    df[col] = df[col].fillna(df[col].mode()[0])

In [28]:
integer_columns = [
    "Age",
    "Login_Frequency",
    "Wishlist_Items",
    "Customer_Service_Calls",
    "Product_Reviews_Written",
    "Payment_Method_Diversity",
    "Churned"
]

for col in integer_columns:
    df[col] = df[col].round().astype(int)

In [29]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [30]:
print("Total duplicated rows:", df.duplicated().sum())

Total duplicated rows: 0

In [31]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50000 entries, 0 to 49999
Data columns (total 25 columns):
 #   Column                         Non-Null Count  Dtype
---  ------                         --------------  -----
 0   Age                            50000 non-null  int64
 1   Gender                         50000 non-null  object
 2   Country                        50000 non-null  object
 3   City                           50000 non-null  object
 4   Membership_Years               50000 non-null  float64
 5   Login_Frequency                50000 non-null  int64
 6   Session_Duration_Avg           50000 non-null  float64
 7   Pages_Per_Session              50000 non-null  float64
 8   Cart_Abandonment_Rate          50000 non-null  float64
 9   Wishlist_Items                 50000 non-null  int64
 10  Total_Purchases                50000 non-null  float64
 11  Average_Order_Value            50000 non-null  float64
 12  Days_Since_Last_Purchase       50000 non-null  float64
 13  Discount_Usage_Rate            50000 non-null  float64
 14  Returns_Rate                   50000 non-null  float64
 15  Email_Open_Rate                50000 non-null  float64
 16  Customer_Service_Calls         50000 non-null  int64
 17  Product_Reviews_Written        50000 non-null  int64
 18  Social_Media_Engagement_Score  50000 non-null  float64
 19  Mobile_App_Usage               50000 non-null  float64
 20  Payment_Method_Diversity       50000 non-null  int64
 21  Lifetime_Value                 50000 non-null  float64
 22  Credit_Balance                 50000 non-null  float64
 23  Churned                        50000 non-null  int64
 24  Signup_Quarter                 50000 non-null  object
dtypes: float64(14), int64(7), object(4)
memory usage: 9.5+ MB

In [32]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
Age,50000.0,37.775400,11.156026,18.00,30.0000,38.000,45.00,75.000000
Membership_Years,50000.0,2.984009,2.059105,0.10,1.4000,2.500,4.00,10.000000
Login_Frequency,50000.0,11.624660,7.810657,0.00,6.0000,11.000,17.00,46.000000
Session_Duration_Avg,50000.0,27.602240,10.497234,1.00,20.2000,26.800,34.00,75.600000
Pages_Per_Session,50000.0,8.717542,3.663996,1.00,6.2000,8.400,11.00,24.100000
Cart_Abandonment_Rate,50000.0,57.043036,16.206917,0.00,46.4000,58.100,68.70,100.000000
Wishlist_Items,50000.0,4.274520,3.060573,0.00,2.0000,4.000,6.00,28.000000
Total_Purchases,50000.0,13.126160,6.995480,0.00,8.0000,12.000,17.00,128.700000
Average_Order_Value,50000.0,123.117330,175.569714,26.38,87.0500,112.970,144.44,9666.379178
Days_Since_Last_Purchase,50000.0,29.265300,28.866043,0.00,9.0000,21.000,39.00,287.000000
Discount_Usage_Rate,50000.0,41.594245,20.204854,0.24,26.5000,40.100,55.20,99.960000
Returns_Rate,50000.0,6.565861,5.872081,0.00,3.1000,5.400,8.60,99.615734
Email_Open_Rate,50000.0,20.875388,13.890225,0.00,10.5000,19.700,29.70,91.700000
Customer_Service_Calls,50000.0,5.679540,2.671844,0.00,4.0000,5.000,7.00,21.000000
Product_Reviews_Written,50000.0,2.793580,2.256482,0.00,1.0000,2.000,4.00,21.000000
Social_Media_Engagement_Score,50000.0,29.152730,19.308632,0.00,15.3000,27.600,40.70,100.000000
Mobile_App_Usage,50000.0,19.294446,8.938875,0.00,13.2000,18.600,24.60,61.900000
Payment_Method_Diversity,50000.0,2.336180,1.084650,1.00,2.0000,2.000,3.00,5.000000
Lifetime_Value,50000.0,1440.626292,907.249443,0.00,789.8175,1243.415,1874.00,8987.240000
Credit_Balance,50000.0,1958.507600,1155.938248,0.00,1164.0000,1896.000,2664.00,7197.000000
Churned,50000.0,0.289000,0.453302,0.00,0.0000,0.000,1.00,1.000000

In [34]:
print(df["Churned"].value_counts())

Churned
0    35550
1    14450
Name: count, dtype: int64

In [35]:
print(df["Churned"].value_counts(normalize=True) * 100)

Churned
0    71.1
1    28.9
Name: proportion, dtype: float64

In [36]:
print("Dataset shape:", df.shape)
print("Missing values:", df.isnull().sum().sum())
print("Duplicates:", df.duplicated().sum())
print("Columns:", df.shape[1])

Dataset shape: (50000, 25)
Missing values: 0
Duplicates: 0
Columns: 25

In [37]:
df.to_csv("ecommerce_customer_churn_cleaned.csv", index=False)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [ ]:
df.to_excel("ecommerce_customer_churn_cleaned.xlsx", index=False)